# permissions for end users to view clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: client-viewer-role
rules:
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - clients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - clients/status
  verbs:
  - get
