# permissions for end users to view upstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upstream-viewer-role
rules:
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - upstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - upstreams/status
  verbs:
  - get
