apiVersion: v1
entries:
  frp-operator:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2022-06-25T01:00:38.759886+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: e2c91089be33642386e6e0eb98c3316ef38ee8c2bc0e3cde1be8789364778be8
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.0.0.tgz
    version: 1.0.0
generated: "2022-06-25T01:00:38.757303+07:00"
