apiVersion: v1
entries:
  frp-operator:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2022-06-25T02:21:03.88567+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 5f80631b3ce1dad5ed2039abb144506fa5795d378f4d465d33c475f216b77df1
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.0.0.tgz
    version: 1.0.0
generated: "2022-06-25T02:21:03.882101+07:00"
