apiVersion: v1
entries:
  frp-operator:
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2024-04-13T22:50:20.361732+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 96f342725e362414480ad385e0ad6db348754e8e3bf5db0d9a7e74ee9c5905a7
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-04-13T22:50:20.360889+07:00"
    description: Expose your service in Kubernetes to the Internet with open source
      FRP!
    digest: 5f80631b3ce1dad5ed2039abb144506fa5795d378f4d465d33c475f216b77df1
    home: https://github.com/zufardhiyaulhaq/frp-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: frp-operator
    type: application
    urls:
    - frp-operator-1.0.0.tgz
    version: 1.0.0
generated: "2024-04-13T22:50:20.359307+07:00"
